version: "3.8"

services:
  server:
    build: ./backend
    container_name: datapop_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: datapop_frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
    stdin_open: true
    tty: true
